=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RBACApiClient::AllPrincipalsPaginationAllOfData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RBACApiClient::AllPrincipalsPaginationAllOfData do
  let(:instance) { RBACApiClient::AllPrincipalsPaginationAllOfData.new }

  describe 'test an instance of AllPrincipalsPaginationAllOfData' do
    it 'should create an instance of AllPrincipalsPaginationAllOfData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RBACApiClient::AllPrincipalsPaginationAllOfData)
    end
  end

  describe 'test attribute "service_accounts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "users"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
